version: '3'
services:
  bighp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - configs:/etc/big-hp
    ports:
      - "443:8000"
    env_file:
      - big-hp.env
volumes:
  configs:
